version: '3.8'

services:
  ytm-downloader:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ytm-downloader
    volumes:
      # Mount the downloads folder from host to container
      - ./downloads:/downloads
      # Mount the logs folder for persistent logs
      - ./logs:/logs
      # Optionally mount a file with playlist URLs
      - ${PLAYLIST_FILE:-./playlists.txt}:/app/playlists.txt:ro
      # Mount custom config file if provided
      - ${CONFIG_FILE:-./config.yml}:/app/config.yml:ro
    environment:
      - OUTPUT_DIR=/downloads
      - MP3_QUALITY=${MP3_QUALITY:-320k}
      - RATE_LIMIT=${RATE_LIMIT:-0}
      - MAX_RETRIES=${MAX_RETRIES:-3}
      - VERBOSE=${VERBOSE:-0}
      - LOG_FILE=${LOG_FILE:-/logs/ytm-downloader.log}
    # Override the default command to use playlists.txt file
    command: -f /app/playlists.txt -o /downloads ${EXTRA_ARGS}
    # Ensure container stops gracefully
    stop_signal: SIGINT
    # Restart policy
    restart: "no"
